version: '3.9'

services:

  mongodb:
    container_name: waiterdb_mongo
    image: 'mongo:latest'
    environment:
       MONGO_INITDB_DATABASE: waiterapp
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27017:27017
    networks:
      - waiterapp_network

  postgresDb:
    image: postgres:16
    restart: always
    environment:
       POSTGRES_DB: waiterappdb
       POSTGRES_PASSWORD: root
       POSTGRES_USER: root
    ports:
      - '5432:5432'
    volumes:
      - pgData:/var/lib/postgresql
    networks:
      - waiterapp_network

  redisCache:
    image: redis:latest
    restart: always
    volumes:
      - cache:/data
    ports:
      - '6379:6379'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - waiterapp_network
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
     -  waiterapp_network



volumes:
  pgData:
  cache:

networks:
  waiterapp_network:
    driver: bridge