version: '3.9'

services:
  app:
    container_name: waiter_app
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
      - mongodb


  mongodb:
    container_name: waiterdb_mongo
    image: 'mongo:latest'
    environment:
       MONGO_INITDB_DATABASE: waiterapp
       MONGO_INITDB_ROOT_PASSWORD: root
       MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - 27017:27017

  postgres:
    container_name: waiterdb_postgres
    image: postgres:16
    restart: always
    environment:
       POSTGRES_DB: waiterappdb
       POSTGRES_PASSWORD: root
       POSTGRES_USER: root
    ports:
      - '5432:5432'
    volumes:
      - pgData:/var/lib/postgresql



volumes:
  pgData:

networks:
  waiterapp_network:
    driver: bridge