global:
  scrape_interval:
  scrape_timeout:
  evaluation_interval: 1m

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets:
        - server1:5432
    metrics_path: /probe

  - job_name: 'waiterapp'
    scrape_interval: 1m
    scrape_timeout: 10s
    static_configs:
      - targets:
        -  web:8080
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
