spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/waiterappdb
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: waiterapp
      port: 27017
      host: localhost
      auto-index-creation: true
  flyway:
    enabled: true