name: dev
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run all Tests 
      run: mvn -B test --file ./pom.xml

  generate_coverage:
    needs: ['tests']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/test/java/**/**/*Test'
      
  build:
    needs: ['generate_coverage']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Get Cache from local repository
      uses: actions/cache@v4.0.2
      with:
        path: ~/.m2 
        key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
        restore-keys: ${{ runner.os }}-maven- 
    - name: Lint Code
      uses: lukasmwerner/prettier_action_java@v1.1.1
      with:
        commit_message: Lint COde
        # Commit options
 #       commit_options: # optional
        # File pattern used for `git add`
  #      file_pattern: # optional, default is 
        # Options for the `prettier` command
   #     prettier_options: # optional, default is --write **/*.java
        # Target branch for the changes
        branch: dev 
        # Running the script in dry mode just shows whether there are files that should be prettified or not
     #  dry: # optional
        # Specific version of prettier (by default just use the latest version)
      #  prettier_version: # optional
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dmaven.Test.skip


